deterministic: true
seed : 42
data_path: "data/data_self_dump.json"
log_dir: "logs"
model_ckpt: "bert-base-uncased"
train:
  lr: 0.0005
  # Training hyperparameters
  n_support : 4
  n_query : 5
  n_episodes : 20
  n_classes : 3
  eval_batch_size : 16
  num_epochs: 5
