deterministic: true
seed : 42
data_path: "data/data_self_dump.json"
model_ckpt: "bert-base-uncased"
device: "cuda"
train:
  lr: 0.0005
  n_epochs: 1 #5
  n_support : 4
  n_query : 5
  n_episodes : 1 #20
  n_classes : 3
  eval_batch_size : 16
  output_dir: "out"
  max_grad_norm: 0


logging:
  log_dir: "logs"
  log_interval: 1 #episodes

# WANDB parameters.
wandb:
  use_wandb: True
  project_name: "LyricStyleSpace"
  exp_name: "LyricStyleSpace_train"